# то из чего будут создаваться контейнеры
services:
  web:
    build:
      # путь к Dockerfile
      context: .
    ports:
      - "8000:8000"
    volumes:
    # локальную папку подключили внутрь контейнера (локальная папка / внутри контейнера)
      - ./service:/service

    # команда для запуска django сервера внутри докера
    # sh -c это шел линукса для запуска
    # 0.0.0.0 - значит все IP-адреса
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
