# Generated by Django 4.2.7 on 2024-02-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uslugi', '0002_subscription_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='comment',
            field=models.CharField(blank=True, max_length=250, verbose_name='Комментарий'),
        ),
    ]
